---
- name: Install Grafana
  hosts: localhost
  connection: local
  become: yes


  tasks:
    - name: Add Jenkins apt repository key
      ansible.builtin.get_url:
        url: https://pkg.jenkins.io/debian/jenkins.io-2023.key
        dest: /usr/share/keyrings/jenkins-keyring.asc
        state: present

    - name: Add jenkins repo to sources.list
      ansible.builtin.apt_repository:
        repo: deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] \ https://pkg.jenkins.io/debian binary/
        filename: jenkins
        state: present

    - name: Update apt cache and install jenkins
      ansible.builtin.apt:
        name: jenkins
        update_cache: yes

    - name: Ensure jenkins is started and enabled
      ansible.builtin.systemd:
        name: jenkins
        enabled: yes
        state: started