---
- name: Install Grafana
  hosts: localhost
  connection: local
  become: yes

  tasks:
  - name: Download apt key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present

  - name: Add Grafana to sources.list
    ansible.builtin.apt_repository:
     repo: deb https://packages.grafana.com/oss/deb stable main
     filename: grafana
     state: present

  - name: Update the apt cache and install Grafana
    ansible.builtin.apt:
     name: grafana
     update_cache: yes

  - name: Ensure Grafana is started and enabled
    ansible.builtin.systemd:
      name: grafana-server
      enabled: true
      state: started

  - name: Download Prometheus
    ansible.builtin.get_url:
      url: https://github.com/prometheus/prometheus/releases/download/v2.30.3/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu

  - name: Extract prom resources
    ansible.builtin.unarchive:
      src: /home/ubuntu/prometheus-2.30.3.linux-amd64.tar.gz
      dest: /home/ubuntu
      remote_src: yes

  - name: Create Prom Group
    ansible.builtin.group:
      name: prometheus
      state: present

  - name: Create Prom User
    ansible.builtin.user:
      name: prometheus
      group: prometheus
      shell: /sbin/nologin

  - name: Create prom directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: true
      owner: prometheus
      group: prometheus
      mode: "0755"
    loop:
      - /etc/prometheus
      - /etc/prometheus/rules
      - /etc/prometheus/rules.d
      - /etc/prometheus/files_sd
      - /var/lib/prometheus
  # - name: Set permissions
  # - name: Copy files
  # - name: Copy Files
  # - name: Create config file
  # - name: Ensure prom is started